"""
Authenticity Data Model
Measures internal profile consistency and coherence.
"""

from dataclasses import dataclass, field


@dataclass
class AuthenticityProfile:
    """
    Profile consistency analysis.
    Generated by the Authenticity Engine.
    """
    candidate_id: str = ""
    semantic_coherence: float = 0.0  # summary vs career alignment
    career_coherence: float = 0.0  # career progression consistency
    evidence_alignment: float = 0.0  # skills vs experience alignment
    timeline_consistency: float = 0.0  # chronological validity
    education_alignment: float = 0.0  # education vs career relevance
    profile_support: float = 0.0  # headline vs summary vs career
    overall_authenticity: float = 0.0  # combined score
    inconsistencies: list[str] = field(default_factory=list)
