"""
Behavioral Intelligence Data Model
Captures candidate engagement and platform behavior.
"""

from dataclasses import dataclass, field


@dataclass
class BehavioralProfile:
    """
    Behavioral analysis results.
    Generated by the Behavioral Intelligence Engine.
    """
    candidate_id: str = ""
    engagement_score: float = 0.0  # overall engagement
    responsiveness_score: float = 0.0  # recruiter response behavior
    activity_score: float = 0.0  # platform activity level
    recruiter_interest_score: float = 0.0  # recruiter-side signals
    verification_score: float = 0.0  # identity verification level
    hiring_readiness_score: float = 0.0  # readiness indicators
    profile_quality_score: float = 0.0  # profile completeness & quality
    overall_behavioral_score: float = 0.0  # combined score
    behavioral_flags: list[str] = field(default_factory=list)
