"""
Candidate Data Model
Strongly typed representation of a candidate profile.
All downstream modules consume this object instead of raw JSON.
"""

from dataclasses import dataclass, field
from typing import Optional


@dataclass
class Profile:
    """Candidate profile information."""
    anonymized_name: str = ""
    headline: str = ""
    summary: str = ""
    location: str = ""
    country: str = ""
    years_of_experience: float = 0.0
    current_title: str = ""
    current_company: str = ""
    current_company_size: str = ""
    current_industry: str = ""


@dataclass
class CareerEntry:
    """Single career history entry."""
    company: str = ""
    title: str = ""
    start_date: str = ""
    end_date: Optional[str] = None
    duration_months: int = 0
    is_current: bool = False
    industry: str = ""
    company_size: str = ""
    description: str = ""


@dataclass
class Education:
    """Education entry."""
    institution: str = ""
    degree: str = ""
    field_of_study: str = ""
    start_year: int = 0
    end_year: int = 0
    grade: Optional[str] = None
    tier: str = "unknown"


@dataclass
class Skill:
    """Skill entry with proficiency and evidence."""
    name: str = ""
    proficiency: str = "beginner"  # beginner | intermediate | advanced | expert
    endorsements: int = 0
    duration_months: int = 0


@dataclass
class Certification:
    """Certification entry."""
    name: str = ""
    issuer: str = ""
    year: int = 0


@dataclass
class Language:
    """Language proficiency."""
    language: str = ""
    proficiency: str = "basic"  # basic | conversational | professional | native


@dataclass
class SalaryRange:
    """Expected salary range in INR LPA."""
    min_lpa: float = 0.0
    max_lpa: float = 0.0


@dataclass
class RedrobSignals:
    """Platform behavioral signals from the Redrob ecosystem."""
    profile_completeness_score: float = 0.0
    signup_date: str = ""
    last_active_date: str = ""
    open_to_work_flag: bool = False
    profile_views_received_30d: int = 0
    applications_submitted_30d: int = 0
    recruiter_response_rate: float = 0.0
    avg_response_time_hours: float = 0.0
    skill_assessment_scores: dict = field(default_factory=dict)
    connection_count: int = 0
    endorsements_received: int = 0
    notice_period_days: int = 0
    expected_salary_range: Optional[SalaryRange] = None
    preferred_work_mode: str = "flexible"
    willing_to_relocate: bool = False
    github_activity_score: float = -1.0
    search_appearance_30d: int = 0
    saved_by_recruiters_30d: int = 0
    interview_completion_rate: float = 0.0
    offer_acceptance_rate: float = -1.0
    verified_email: bool = False
    verified_phone: bool = False
    linkedin_connected: bool = False


@dataclass
class CandidateObject:
    """
    Complete structured representation of a candidate.
    Generated by the Candidate Parser.
    This is the ONLY candidate representation used by downstream modules.
    """
    candidate_id: str = ""
    profile: Profile = field(default_factory=Profile)
    career_history: list[CareerEntry] = field(default_factory=list)
    education: list[Education] = field(default_factory=list)
    skills: list[Skill] = field(default_factory=list)
    certifications: list[Certification] = field(default_factory=list)
    languages: list[Language] = field(default_factory=list)
    redrob_signals: RedrobSignals = field(default_factory=RedrobSignals)

    @property
    def skill_names(self) -> list[str]:
        """Get list of skill names."""
        return [s.name for s in self.skills]

    @property
    def total_career_months(self) -> int:
        """Total career duration in months."""
        return sum(e.duration_months for e in self.career_history)

    @property
    def num_companies(self) -> int:
        """Number of companies worked at."""
        return len(self.career_history)

    @property
    def career_text(self) -> str:
        """Combined career description text."""
        return " ".join(
            f"{e.title} at {e.company}: {e.description}"
            for e in self.career_history
            if e.description
        )
