"""
Evidence Intelligence Data Model
Measures how strongly candidate claims are supported by evidence.
"""

from dataclasses import dataclass, field


@dataclass
class CompetencyEvidence:
    """Evidence for a single competency."""
    competency_name: str = ""
    mentioned_in_skills: bool = False
    mentioned_in_summary: bool = False
    mentioned_in_career: bool = False
    mentioned_in_certifications: bool = False
    assessment_score: float = -1.0  # -1 = no assessment
    endorsement_count: int = 0
    skill_duration_months: int = 0
    career_mentions_count: int = 0
    source_count: int = 0  # total evidence sources
    confidence: float = 0.0  # 0.0 to 1.0


@dataclass
class EvidenceProfile:
    """
    Complete evidence analysis for a candidate.
    Generated by the Evidence Intelligence Engine.
    """
    candidate_id: str = ""
    competency_evidence: list[CompetencyEvidence] = field(default_factory=list)
    overall_evidence_score: float = 0.0
    evidence_coverage: float = 0.0  # fraction of required competencies with evidence
    evidence_density: float = 0.0  # avg sources per competency
    strong_evidence_count: int = 0  # competencies with high confidence
    weak_evidence_count: int = 0  # competencies with low confidence
    unsupported_claims: list[str] = field(default_factory=list)
