"""
Explanation Data Model
Deterministic, traceable explanations for ranked candidates.
"""

from dataclasses import dataclass, field


@dataclass
class CandidateExplanation:
    """
    Deterministic explanation for a ranked candidate.
    Generated by the Explainability Engine.
    Every sentence maps to a computed feature.
    """
    candidate_id: str = ""
    rank: int = 0
    score: float = 0.0

    # Explanation components
    strengths: list[str] = field(default_factory=list)
    supporting_evidence: list[str] = field(default_factory=list)
    improvement_areas: list[str] = field(default_factory=list)
    decision_trace: list[str] = field(default_factory=list)

    # Module contributions
    module_contributions: dict[str, float] = field(default_factory=dict)

    # Human-readable reasoning (for submission CSV)
    reasoning: str = ""

    # Confidence
    confidence_summary: str = ""
