"""
Feature Vector Data Model
Machine-readable representation of candidate attributes.
Generated by the Adaptive Feature Engineering Engine.
"""

from dataclasses import dataclass, field
import numpy as np


@dataclass
class ProfileFeatures:
    """Features extracted from candidate profile."""
    years_experience: float = 0.0
    years_experience_percentile: float = 0.0
    title_relevance: float = 0.0
    industry_relevance: float = 0.0
    company_size_encoded: float = 0.0
    headline_similarity: float = 0.0
    summary_similarity: float = 0.0


@dataclass
class TechnicalFeatures:
    """Technical skill features."""
    total_skills: int = 0
    relevant_skills_count: int = 0
    relevant_skills_ratio: float = 0.0
    avg_proficiency: float = 0.0
    avg_endorsements: float = 0.0
    avg_skill_duration: float = 0.0
    advanced_expert_ratio: float = 0.0
    skill_coverage: float = 0.0  # fraction of required skills possessed
    assessment_score_avg: float = 0.0
    relevant_assessment_avg: float = 0.0
    certification_count: int = 0


@dataclass
class CareerFeatures:
    """Career history features."""
    total_companies: int = 0
    total_career_months: int = 0
    avg_tenure_months: float = 0.0
    current_tenure_months: int = 0
    career_description_similarity: float = 0.0
    relevant_experience_months: int = 0
    startup_experience: bool = False
    large_company_experience: bool = False


@dataclass
class EducationFeatures:
    """Education features."""
    highest_degree_level: int = 0  # 0=none, 1=bachelor, 2=master, 3=phd
    field_relevance: float = 0.0
    institution_tier: int = 4  # 1=tier_1, 2=tier_2, 3=tier_3, 4=tier_4/unknown
    education_count: int = 0


@dataclass
class BehavioralFeatures:
    """Raw behavioral features (before intelligence analysis)."""
    profile_completeness: float = 0.0
    days_since_signup: int = 0
    days_since_active: int = 0
    open_to_work: bool = False
    profile_views_30d: int = 0
    applications_30d: int = 0
    response_rate: float = 0.0
    avg_response_time: float = 0.0
    connection_count: int = 0
    endorsements_received: int = 0
    notice_period_days: int = 0
    github_activity: float = -1.0
    search_appearances_30d: int = 0
    saved_by_recruiters_30d: int = 0
    interview_completion_rate: float = 0.0
    offer_acceptance_rate: float = -1.0
    verified_email: bool = False
    verified_phone: bool = False
    linkedin_connected: bool = False
    willing_to_relocate: bool = False
    preferred_work_mode: str = "flexible"


@dataclass
class SemanticFeatures:
    """Semantic similarity features."""
    summary_jd_similarity: float = 0.0
    career_jd_similarity: float = 0.0
    skills_jd_similarity: float = 0.0
    headline_jd_similarity: float = 0.0
    overall_semantic_score: float = 0.0
    concept_overlap_score: float = 0.0
    summary_embedding: list[float] = field(default_factory=list)
    career_embedding: list[float] = field(default_factory=list)


@dataclass
class StatisticalFeatures:
    """Corpus-relative statistical features."""
    experience_z_score: float = 0.0
    skills_z_score: float = 0.0
    endorsements_z_score: float = 0.0
    response_rate_z_score: float = 0.0
    completeness_z_score: float = 0.0


@dataclass
class FeatureVector:
    """
    Complete feature representation of a candidate.
    Generated by the Adaptive Feature Engineering Engine.
    Consumed by all downstream intelligence modules.
    """
    candidate_id: str = ""
    profile_features: ProfileFeatures = field(default_factory=ProfileFeatures)
    technical_features: TechnicalFeatures = field(default_factory=TechnicalFeatures)
    career_features: CareerFeatures = field(default_factory=CareerFeatures)
    education_features: EducationFeatures = field(default_factory=EducationFeatures)
    behavioral_features: BehavioralFeatures = field(default_factory=BehavioralFeatures)
    semantic_features: SemanticFeatures = field(default_factory=SemanticFeatures)
    statistical_features: StatisticalFeatures = field(default_factory=StatisticalFeatures)

    # Quick access score for progressive filtering
    cheap_score: float = 0.0

    def to_numpy(self) -> np.ndarray:
        """Convert key numerical features to numpy array for vectorized operations."""
        return np.array([
            self.profile_features.years_experience,
            self.profile_features.title_relevance,
            self.technical_features.relevant_skills_ratio,
            self.technical_features.skill_coverage,
            self.technical_features.assessment_score_avg,
            self.career_features.career_description_similarity,
            self.semantic_features.overall_semantic_score,
            self.behavioral_features.response_rate,
            self.behavioral_features.profile_completeness / 100.0,
        ], dtype=np.float32)
