"""
Hiring Profile Data Model
Dynamic representation of hiring intent extracted from Job Description.
This immutable object drives all downstream intelligence modules.
"""

from dataclasses import dataclass, field


@dataclass
class Competency:
    """A single competency extracted from the JD."""
    name: str = ""
    category: str = "mandatory"  # mandatory | preferred | nice_to_have
    importance: float = 0.0  # 0.0 to 1.0, dynamically computed
    related_concepts: list[str] = field(default_factory=list)
    section_source: str = ""  # which JD section this came from


@dataclass
class SemanticConcept:
    """A semantic concept cluster from the JD."""
    primary_term: str = ""
    related_terms: list[str] = field(default_factory=list)
    embedding: list[float] = field(default_factory=list)
    importance: float = 0.0


@dataclass
class HiringConstraint:
    """An explicit hiring constraint from the JD."""
    name: str = ""
    value: str = ""
    constraint_type: str = "preference"  # requirement | preference | disqualifier
    description: str = ""


@dataclass
class HiringPhilosophy:
    """Latent hiring preferences extracted from JD narrative."""
    dimension: str = ""  # e.g., "product_mindset", "startup_adaptability"
    strength: float = 0.0  # 0.0 to 1.0
    evidence: str = ""  # JD text supporting this


@dataclass
class ExperienceExpectation:
    """Experience requirements from the JD."""
    min_years: float = 0.0
    max_years: float = 50.0
    preferred_years: float = 0.0
    seniority_level: str = ""  # junior | mid | senior | lead | staff


@dataclass
class RoleMetadata:
    """Metadata about the target role."""
    title: str = ""
    department: str = ""
    company: str = ""
    industry: str = ""
    work_mode: str = "flexible"  # remote | hybrid | onsite | flexible
    location: str = ""


@dataclass
class HiringProfile:
    """
    Dynamic Hiring Profile — the 'brain' of the system.
    Generated by the JD Intelligence Engine.
    Every downstream module references this object.
    This object is IMMUTABLE after creation.
    """
    # Competencies
    required_competencies: list[Competency] = field(default_factory=list)
    preferred_competencies: list[Competency] = field(default_factory=list)

    # Semantic understanding
    semantic_concepts: list[SemanticConcept] = field(default_factory=list)
    jd_embeddings: list[list[float]] = field(default_factory=list)
    jd_full_text: str = ""
    jd_sections: dict = field(default_factory=dict)

    # Hiring intelligence
    hiring_constraints: list[HiringConstraint] = field(default_factory=list)
    hiring_philosophy: list[HiringPhilosophy] = field(default_factory=list)
    experience_expectation: ExperienceExpectation = field(default_factory=ExperienceExpectation)
    role_metadata: RoleMetadata = field(default_factory=RoleMetadata)

    # Dynamic priorities (computed from JD analysis)
    feature_importance: dict[str, float] = field(default_factory=dict)
    competency_priorities: dict[str, float] = field(default_factory=dict)

    # Behavioral expectations
    behavioral_expectations: list[str] = field(default_factory=list)
    disqualifiers: list[str] = field(default_factory=list)

    @property
    def all_competency_names(self) -> list[str]:
        """All competency names (required + preferred)."""
        return [c.name for c in self.required_competencies + self.preferred_competencies]

    @property
    def required_skill_names(self) -> list[str]:
        """Required skill names only."""
        return [c.name for c in self.required_competencies]
