"""
Career Narrative Data Model
Models professional evolution and career trajectory.
"""

from dataclasses import dataclass, field


@dataclass
class CareerTransition:
    """A single career transition."""
    from_title: str = ""
    to_title: str = ""
    from_industry: str = ""
    to_industry: str = ""
    transition_quality: float = 0.0  # semantic similarity
    is_advancement: bool = False
    is_lateral: bool = False
    is_specialization: bool = False


@dataclass
class NarrativeProfile:
    """
    Career narrative analysis.
    Generated by the Career Narrative Engine.
    """
    candidate_id: str = ""
    career_progression: float = 0.0  # overall progression quality
    specialization_trend: float = 0.0  # trend toward relevant specialization
    growth_score: float = 0.0  # evidence of professional growth
    technical_evolution: float = 0.0  # technical skill expansion
    domain_alignment: float = 0.0  # alignment with target role domain
    leadership_evolution: float = 0.0  # progression toward leadership
    narrative_strength: float = 0.0  # overall narrative quality
    transitions: list[CareerTransition] = field(default_factory=list)
    career_direction: str = ""  # ascending | lateral | mixed | declining
