"""
Ranking Data Model
Final ranking results and unified candidate representation.
"""

from dataclasses import dataclass, field
from models.feature_vector import FeatureVector
from models.evidence import EvidenceProfile
from models.authenticity import AuthenticityProfile
from models.narrative import NarrativeProfile
from models.behavior import BehavioralProfile
from models.recruitability import RecruitabilityProfile


@dataclass
class UnifiedCandidateProfile:
    """
    Complete candidate representation combining all intelligence modules.
    Generated by the Feature Fusion Engine.
    This is the ONLY object consumed by the Ranking Engine.
    """
    candidate_id: str = ""
    feature_vector: FeatureVector = field(default_factory=FeatureVector)
    evidence_profile: EvidenceProfile = field(default_factory=EvidenceProfile)
    authenticity_profile: AuthenticityProfile = field(default_factory=AuthenticityProfile)
    narrative_profile: NarrativeProfile = field(default_factory=NarrativeProfile)
    behavioral_profile: BehavioralProfile = field(default_factory=BehavioralProfile)
    recruitability_profile: RecruitabilityProfile = field(default_factory=RecruitabilityProfile)

    # Fused scores (normalized, comparable)
    fused_technical: float = 0.0
    fused_semantic: float = 0.0
    fused_evidence: float = 0.0
    fused_authenticity: float = 0.0
    fused_narrative: float = 0.0
    fused_behavioral: float = 0.0
    fused_recruitability: float = 0.0


@dataclass
class RankingMetadata:
    """Metadata explaining the ranking decision."""
    dominant_strengths: list[str] = field(default_factory=list)
    supporting_modules: list[str] = field(default_factory=list)
    feature_contributions: dict[str, float] = field(default_factory=dict)
    decision_trace: list[str] = field(default_factory=list)
    ranking_confidence: float = 0.0


@dataclass
class RankedCandidate:
    """
    Final ranked candidate with decision metadata.
    Generated by the Ranking Engine.
    """
    candidate_id: str = ""
    final_rank: int = 0
    final_score: float = 0.0
    unified_profile: UnifiedCandidateProfile = field(default_factory=UnifiedCandidateProfile)
    ranking_metadata: RankingMetadata = field(default_factory=RankingMetadata)
    candidate_name: str = ""
    current_title: str = ""
    years_experience: float = 0.0
