"""
Recruitability Data Model
Estimates hiring feasibility based on practical constraints.
"""

from dataclasses import dataclass, field


@dataclass
class RecruitabilityProfile:
    """
    Recruitability analysis results.
    Generated by the Recruitability Engine.
    """
    candidate_id: str = ""
    availability_score: float = 0.0  # notice period, open to work
    hiring_compatibility: float = 0.0  # constraint satisfaction
    constraint_compatibility: float = 0.0  # work mode, location
    behavioral_support: float = 0.0  # behavioral readiness for hiring
    recruiter_success_estimate: float = 0.0  # estimated hiring probability
    recruitability_score: float = 0.0  # overall score
    compatibility_details: dict = field(default_factory=dict)
